In [14]:
# # Import the required libraries

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# from typing import List, Tuple

# %matplotlib inline

In [15]:
# df = pd.read_excel('train.xls')
# df.head(20)

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

In [17]:
train_df = pd.read_excel('train.xls')
test_df = pd.read_excel('test.xlsx')

print(train_df.columns)

Index(['Training set', 'Mouth', 'Oesophagus', 'Stomach', 'Duodenum', 'Ileum',
       'A-Colon', 'T-Colon', 'D-Colon', 'Rectum', 'Perianal', 'Mouth.1',
       'Oesophagus.1', 'Stomach.1', 'Duodenum.1', 'Ileum.1', 'A-Colon.1',
       'T-Colon.1', 'D-Colon.1', 'Rectum.1', 'Perianal.1', 'Diagnosis'],
      dtype='object')


In [18]:
# Separate features (X) and target (y) for training dataset
# Separate features (X) and target (y) for training dataset
X_train = train_df.drop(['Diagnosis', 'Training set'], axis=1)
y_train = train_df['Diagnosis']


X_test = test_df.drop(['Diagnosis', 'Training set'], axis=1)
y_test = test_df['Diagnosis']



In [19]:
print(X_train.dtypes)


Mouth           int64
Oesophagus      int64
Stomach         int64
Duodenum        int64
Ileum           int64
A-Colon         int64
T-Colon         int64
D-Colon         int64
Rectum          int64
Perianal        int64
Mouth.1         int64
Oesophagus.1    int64
Stomach.1       int64
Duodenum.1      int64
Ileum.1         int64
A-Colon.1       int64
T-Colon.1       int64
D-Colon.1       int64
Rectum.1        int64
Perianal.1      int64
dtype: object


In [20]:
non_numeric_values = X_train['Stomach'].apply(lambda x: not isinstance(x, (int, np.int64)))
print(non_numeric_values.any())


False


In [21]:
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

In [22]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train_encoded)

DecisionTreeClassifier()

In [23]:
print("Columns in X_train:", X_train.columns)
print("Columns in X_test:", X_test.columns)


Columns in X_train: Index(['Mouth', 'Oesophagus', 'Stomach', 'Duodenum', 'Ileum', 'A-Colon',
       'T-Colon', 'D-Colon', 'Rectum', 'Perianal', 'Mouth.1', 'Oesophagus.1',
       'Stomach.1', 'Duodenum.1', 'Ileum.1', 'A-Colon.1', 'T-Colon.1',
       'D-Colon.1', 'Rectum.1', 'Perianal.1'],
      dtype='object')
Columns in X_test: Index(['Mouth', 'Oesophagus', 'Stomach', 'Duodenum', 'Ileum', 'A-Colon',
       'T-Colon', 'D-Colon', 'Rectum', 'Perianal', 'Mouth.1', 'Oesophagus.1',
       'Stomach.1', 'Duodenum.1', 'Ileum.1', 'A-Colon.1', 'T-Colon.1',
       'D-Colon.1', 'Rectum.1', 'Perianal.1'],
      dtype='object')


In [24]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_test_pred_encoded = clf.predict(X_test)

# Evaluate the model on the testing data
test_accuracy = accuracy_score(y_test_encoded, y_test_pred_encoded)
test_classification_report = classification_report(y_test_encoded, y_test_pred_encoded, zero_division=1)
test_confusion_matrix = confusion_matrix(y_test_encoded, y_test_pred_encoded)




In [25]:
print("Test Accuracy:", test_accuracy)
print("\nClassification Report:\n", test_classification_report)
print("\nConfusion Matrix:\n", test_confusion_matrix)


Test Accuracy: 0.7083333333333334

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.80      0.82        35
           1       0.00      1.00      0.00         0
           2       0.67      0.46      0.55        13

    accuracy                           0.71        48
   macro avg       0.51      0.75      0.46        48
weighted avg       0.80      0.71      0.75        48


Confusion Matrix:
 [[28  4  3]
 [ 0  0  0]
 [ 5  2  6]]


Test Accuracy: This is a measure of how accurately your model predicts the target variable on the testing data. It's the ratio of correctly predicted samples to the total number of samples in the testing dataset. Higher accuracy values indicate better model performance.

Classification Report: This report provides detailed metrics for each class in your dataset. For each class, it includes the following:

Precision: Precision measures how many of the predicted positive instances for a class were actually positive. It's the ratio of true positives to the sum of true positives and false positives.
Recall: Recall (or true positive rate) measures how many of the actual positive instances for a class were correctly predicted. It's the ratio of true positives to the sum of true positives and false negatives.
F1-Score: The F1-score is the harmonic mean of precision and recall. It provides a balance between precision and recall and is often used when dealing with imbalanced datasets.
Support: The support is the number of samples in the testing dataset that belong to each class.
Confusion Matrix: The confusion matrix is a table that summarizes the model's performance by showing the number of true positives, true negatives, false positives, and false negatives. It provides a more detailed breakdown of the model's errors and correct predictions for each class.

In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# ... (code for loading and preprocessing training data)

# Train the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train_encoded)

# ... (code for evaluating the model, including accuracy_score)

# Function to make predictions based on user input
# def predict_diagnosis(user_input):
#     # Preprocess user input
#     user_input_df = pd.DataFrame(user_input, index=[0])
#     # Perform preprocessing steps like encoding, scaling, etc.

#     # Use the trained classifier to make predictions
#     predicted_diagnosis = clf.predict(user_input_df)

#     return predicted_diagnosis[0]

def predict_diagnosis(user_input, label_encoder):
    user_input_df = pd.DataFrame(user_input, index=[0])
    predicted_diagnosis_encoded = clf.predict(user_input_df)
    predicted_diagnosis = label_encoder.inverse_transform(predicted_diagnosis_encoded)
    return predicted_diagnosis[0]

# Collect user input
user_input = {
        'Mouth': float(input("Enter Mouth value: ")),
        'Oesophagus': float(input("Enter Oesophagus value: ")),
        'Stomach': float(input("Enter Stomach value: ")),
        'Duodenum': float(input("Enter Duodenum value: ")),
        'Ileum': float(input("Enter Ileum value: ")),
        'A-Colon': float(input("Enter A-Colon value: ")),
        'T-Colon': float(input("Enter T-Colon value: ")),
        'D-Colon': float(input("Enter D-Colon value: ")),
        'Rectum': float(input("Enter Rectum value: ")),
        'Perianal': float(input("Enter Perianal value: ")),
        'Mouth.1': float(input("Enter Mouth.1 value: ")),
        'Oesophagus.1': float(input("Enter Oesophagus.1 value: ")),
        'Stomach.1': float(input("Enter Stomach.1 value: ")),
        'Duodenum.1': float(input("Enter Duodenum.1 value: ")),
        'Ileum.1': float(input("Enter Ileum.1 value: ")),
        'A-Colon.1': float(input("Enter A-Colon.1 value: ")),
        'T-Colon.1': float(input("Enter T-Colon.1 value: ")),
        'D-Colon.1': float(input("Enter D-Colon.1 value: ")),
        'Rectum.1': float(input("Enter Rectum.1 value: ")),
        'Perianal.1': float(input("Enter Perianal.1 value: ")),
    # ... (collect values for all features)
}

# Initialize a label encoder for the target variable (Diagnosis)
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)

# Make a diagnosis prediction
predicted_diagnosis = predict_diagnosis(user_input, label_encoder)

# Display the predicted diagnosis
print("Predicted Diagnosis:", predicted_diagnosis)

Predicted Diagnosis: Crohn's Disease
